// evmone: Fast Ethereum Virtual Machine implementation
// Copyright 2022 The evmone Authors.
// SPDX-License-Identifier: Apache-2.0

#include <CLI/CLI.hpp>
#include <evmone/evmone.h>
#include <evmone/version.h>
#include <gtest/gtest.h>
#include <test/utils/statetest.hpp>
#include <test/utils/utils.hpp>
#include <evmc/loader.h>
#include <filesystem>
#include <iostream>
#include <memory>
#include "dt_vm.h"

namespace fs = std::filesystem;

namespace
{
namespace vm_manager
{
evmc::VM evmone_advanced{evmc_create_evmone(), {{"advanced", ""}}};
evmc::VM evmone_baseline{evmc_create_evmone()};
evmc::VM external_vm;

std::vector<std::pair<std::string, evmc::VM*>> get_available_vms() {
    static bool initialized = false;
    static bool external_load_state = false;
    std::vector<std::pair<std::string, evmc::VM*>> vms;
    vms.emplace_back("evmone_advanced", &evmone_advanced);
    vms.emplace_back("evmone_baseline", &evmone_baseline);

    // Load external lib
    const char* external_env_options = getenv("EVMONE_EXTERNAL_OPTIONS");
    if (external_env_options != nullptr) {
        if (!initialized) {
            external_load_state = evmone::test::try_load_external(external_env_options, external_vm);
            initialized = true;
        }
    }

    if (external_load_state) {
        vms.emplace_back("external_vm", &external_vm);
    }

    return vms;
}
}  // namespace vm_manager
/// Implementation of a gtest Test which runs all state tests from a given file.
class StateTestFile : public testing::Test
{
    fs::path m_json_test_file;
    std::optional<std::string> m_filter;
    evmc::VM& m_vm;
    bool m_trace = false;

public:
    explicit StateTestFile(fs::path json_test_file, const std::optional<std::string>& filter,
        evmc::VM& vm, bool trace) noexcept
      : m_json_test_file{std::move(json_test_file)}, m_filter{filter}, m_vm{vm}, m_trace{trace}
    {}

    void TestBody() final
    {
        std::ifstream f{m_json_test_file};
        const auto tests = evmone::test::load_state_tests(f);
        for (const auto& test : tests)
        {
            if (m_filter.has_value() && test.name.find(*m_filter) == std::string::npos)
                continue;
            evmone::test::run_state_test(test, m_vm, m_trace);
        }
    }

    static void register_one(const std::string& suite_name, const fs::path& file,
        const std::optional<std::string>& filter, evmc::VM& vm, bool trace)
    {
        testing::RegisterTest(suite_name.c_str(), file.stem().string().c_str(), nullptr, nullptr,
            file.string().c_str(), 0, [file, filter, &vm, trace]() -> testing::Test* {
                return new StateTestFile(file, filter, vm, trace);
            });
    }
};

/// Implementation of a gtest Test which runs a single state test.
class StateTest : public testing::Test
{
    evmone::test::StateTransitionTest m_state_transition_test;
    evmc::VM& m_vm;
    bool m_trace = false;

public:
    explicit StateTest(
        evmone::test::StateTransitionTest state_transition_test, evmc::VM& vm, bool trace) noexcept
      : m_state_transition_test{std::move(state_transition_test)}, m_vm{vm}, m_trace{trace}
    {}

    void TestBody() final { evmone::test::run_state_test(m_state_transition_test, m_vm, m_trace); }

    static void register_one(const evmone::test::StateTransitionTest& test,
        const std::string& suite_name, const std::string& test_name, const fs::path& file,
        evmc::VM& vm, bool trace)
    {
        testing::RegisterTest(suite_name.c_str(), test_name.c_str(), nullptr, nullptr,
            file.string().c_str(), 0,
            [test, &vm, trace]() -> testing::Test* { return new StateTest(test, vm, trace); });
    }
};

void register_test_files(
    const fs::path& root, const std::optional<std::string>& filter, const std::string& vm_name, evmc::VM& vm, bool trace)
{
    if (is_directory(root))
    {
        std::vector<fs::path> test_files;
        std::copy_if(fs::recursive_directory_iterator{root}, fs::recursive_directory_iterator{},
            std::back_inserter(test_files), [](const fs::directory_entry& entry) {
                // "index.json" files are just lists of tests generated by other tools.
                return entry.is_regular_file() && entry.path().extension() == ".json" &&
                       entry.path().filename() != "index.json";
            });
        std::ranges::sort(test_files);

        for (const auto& p : test_files)
        {
            std::string suite_name = vm_name + "/" + fs::relative(p, root).parent_path().string();
            StateTestFile::register_one(suite_name, p, filter, vm, trace);
        }
    }
    else  // Treat as a file.
    {
        std::ifstream f{root};
        const auto tests = evmone::test::load_state_tests(f);
        for (const auto& test : tests)
        {
            if (filter.has_value() && test.name.find(*filter) == std::string::npos)
                continue;
            std::string suite_name = vm_name + "/" + root.string();
            std::string test_name = test.name;
            StateTest::register_one(test, suite_name, test_name, root, vm, trace);
        }
    }
}
}  // namespace


int main(int argc, char* argv[])
{
    // The default test filter. To enable all tests use `--gtest_filter=*`.
    testing::FLAGS_gtest_filter =
        "-"
        // Slow tests:
        "stCreateTest.CreateOOGafterMaxCodesize:"      // pass
        "stQuadraticComplexityTest.Call50000_sha256:"  // pass
        "stTimeConsuming.static_Call50000_sha256:"     // pass
        "stTimeConsuming.CALLBlake2f_MaxRounds:"       // pass
        "VMTests/vmPerformance.*:"                     // pass
        ;

    try
    {
        testing::InitGoogleTest(&argc, argv);  // Process GoogleTest flags.

        CLI::App app{"evmone state test runner"};

        app.set_version_flag("--version", "evmone-statetest " EVMONE_VERSION);

        std::vector<std::string> paths;
        app.add_option("path", paths,
               "Path to test file or directory. For a directory, all .json "
               "files (except index.json) are considered test files, and each file is treated as a "
               "separate test. For a file, all tests in the file are treated as separate tests.")
            ->required()
            ->check(CLI::ExistingPath);

        std::optional<std::string> filter;
        app.add_option("-k", filter,
            "Test name filter. Run only tests with names containing the specified string.");

        bool trace = false;
        bool trace_summary = false;
        const auto trace_opt = app.add_flag("--trace", trace, "Enable EVM tracing");
        app.add_flag("--trace-summary", trace_summary, "Output trace summary only")
            ->excludes(trace_opt);

        std::optional<std::string> vm_filter;
        app.add_option("--vm", vm_filter,
            "VM filter. Run tests only on VMs containing the specified string (e.g., 'external', 'evmone_advanced').");

        CLI11_PARSE(app, argc, argv);

        auto available_vms = vm_manager::get_available_vms();

        if (available_vms.empty())
        {
            std::cerr << "No VMs available for testing\n";
            return -1;
        }

        if (vm_filter.has_value())
        {
            auto filtered_vms = std::vector<std::pair<std::string, evmc::VM*>>{};
            for (const auto& [name, vm] : available_vms)
            {
                if (name.find(*vm_filter) != std::string::npos)
                {
                    filtered_vms.push_back({name, vm});
                }
            }
            available_vms = std::move(filtered_vms);
        }

        if (available_vms.empty())
        {
            std::cerr << "No VMs match the filter: " << *vm_filter << "\n";
            return -1;
        }

        for (const auto& [vm_name, vm_ptr] : available_vms)
        {
            std::cout << "Registering tests for VM: " << vm_name << std::endl;

            if (trace)
            {
                std::ios::sync_with_stdio(false);
                vm_ptr->set_option("trace", "1");
            }

            for (const auto& p : paths)
                register_test_files(p, filter, vm_name, *vm_ptr, trace || trace_summary);
        }

        return RUN_ALL_TESTS();
    }
    catch (const std::exception& ex)
    {
        std::cerr << ex.what() << "\n";
        return -1;
    }
}
